### ISSUE TITLE
groupingを指定した場合の角度、ステップ変換が正しく行えない

### ISSUE THREAD

**Issue by ghost** [UrgNetwork/urg_library#1]
urg_index2rad等の角度、ステップ変換系関数はgroupingを考慮していないため、
groupingを設定した場合にこれらの関数が返す値が正しくなくなる。

**Comment by UrgNetwork** [comment]
USTシリーズではurg_libraryが想定しているVVコマンドの応答ではないため、
バージョン情報が正しく取得できない。
