### ISSUE TITLE
error: implicit declaration of function 'usleep' 

### ISSUE THREAD

**Issue by HgGamer** [UrgNetwork/urg_library#19]
Hello I cannot build it on MAC.

`catfood@Catfoods-MacBook urg_library-1.2.6 % make
cd src/ && /Applications/Xcode.app/Contents/Developer/usr/bin/make
gcc -g -O2  -I../include/c -fPIC   -c -o urg_utils.o urg_utils.c
urg_utils.c:218:5: error: implicit declaration of function 'usleep' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    usleep(1000 * delay_msec);
    ^
1 error generated.
make[1]: *** [urg_utils.o] Error 1
make: *** [all] Error 2
catfood@Catfoods-MacBook urg_library-1.2.6 % `

**Comment by huangda1982** [comment]
As the compiler said, usleep is invalid C99. You can remove "-Werror" in Makefile and try again. It will give a warning instead of error. We may fix this in the next release.

**Comment by HgGamer** [comment]
Thanks, I managed to compile it, with the following header.

```cpp
#include <unistd.h>
```
