### ISSUE TITLE
Discrepancy with regards to scanner steps

### ISSUE THREAD

**Issue by AndersHogqvist** [UrgNetwork/urg_library#23]
According to the library documentation the scanner steps starts with 0 in front of the scanner (https://github.com/UrgNetwork/urg_library/blob/master/current/dox/sensor_step_image.svg)

However, in the scanner specifications it states that the steps starts with 0 at the very right of the scanner (https://hokuyo-usa.com/application/files/7416/0857/9121/UST-10LX_Specifications_REV.pdf)

So what is it? Zero in front or to the right?

**Comment by ghost** [comment]
The UST-10LX specification is measure from the right side of the sensor.

However, when specifying the measurement section with urg_set_scanning_parameter(), the front must be considered as 0 degrees.

 > Observing the sensor from the top, the step 0 corresponds to the very front of the sensor, steps at the left side (counter clockwise) of step 0 are positive numbers and those to the right side (clockwise) are negative numbers.
 ( https://urgnetwork.sourceforge.net/html_ja/urg__sensor_8h.html#a98ea7317a7aced137804a80570b0409e )

**Comment by AndersHogqvist** [comment]
Ok, thanks!
