### ISSUE TITLE
Error number for UAM-05LP-T301

### ISSUE THREAD

**Issue by richardw347** [UrgNetwork/urg_library#24]
Hi,

I'm working with the UAM-05LP safety LIDAR and having an issue with getting the various device error codes from the urg_library. The sensor has a LED panel that displays the error codes and UAM Project Designer is capable of displaying them so I was hoping there might be a way to read the error code from the urg_library. 

This is really important for use because we are using the UAM's on a mobile robot in dusty environments and they are prone to being affected by dust. The sensor has the capability to detect the dusty and report it:

<img width="505" alt="image (15)" src="https://user-images.githubusercontent.com/2834094/224082836-808c3297-4e90-4bf4-87ef-ccdb21af8282.png">

I just haven't been able to get this from the library the best I've been able to do is use: https://github.com/UrgNetwork/urg_library/blob/e41455c7858d24a39332a79412ecb6cfc716839b/current/src/urg_sensor.c#L1438

However this just gives very basic binary "Sensor is working well." or "Sensor is in error state.". It would be extremely helpful to be able to get the Error Number from the sensor and be able to use it in our reporting system so we know that the laser needs to be cleaned.

**Comment by j-fujimoto** [comment]
Hi,

The UAM-05LP supports both the SCIP and Safety protocols, with error codes provided by the latter.
However, the urg_library is designed specifically for use with the SCIP protocol.　
While we may modify it to also support the Safety protocol in the future, there are no current plans to do so.

**Comment by huangda1982** [comment]
> While we may modify it to also support the Safety protocol in the future, there are no current plans to do so.
