### ISSUE TITLE
Question about the is_stable and status functions

### ISSUE THREAD

**Issue by AndersHogqvist** [UrgNetwork/urg_library#26]
I have tried to find some information about what one can expect to get when calling status() and I'm currently waiting for an answer from Hokuyo. All I've seen so far is "sensor is working normally" but then it hit me that perhaps this function is only relevant when is_stable() returns false? Or can status() return something else even though is_stable() returns true?

**Comment by ghost** [comment]
When is_stable() returns true, it never returns anything other than the following sentences.
These sentences have the same meaning as "sensor is working normally".


    return (strncmp("Stable 000 no error", stat, 19) == 0
            || strncmp("Sensor works well", stat, 17) == 0
            || strncmp("sensor is working normally", stat, 26) == 0
            || strncmp("failed to synchronize", stat, 21) == 0
            || strncmp("detected multiple master sensor", stat, 31) == 0) ? 1: 0;


When is_stable() returns false, status() returns the sensor error information.

**Comment by AndersHogqvist** [comment]
Thank you for clarifying
