### ISSUE TITLE
Setting baud rate UTX-10LN

### ISSUE THREAD

**Issue by tstoyanov** [UrgNetwork/urg_library#29]
I am encountering a problem with a UTX-10LN scanner, fresh out of the box. I am trying to connect via the USB front port. The sensor powers on okay, I get a blue indicator light on the front and running dmesg shows the device connecting correctly:
```
[461128.249176] usb 1-4: new full-speed USB device number 75 using xhci_hcd
[461128.377551] usb 1-4: New USB device found, idVendor=15d1, idProduct=0000, bcdDevice= 1.00
[461128.377568] usb 1-4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[461128.377576] usb 1-4: Product: URG-Series USB Driver
[461128.377582] usb 1-4: Manufacturer: Hokuyo Automatic Co, Ltd.
[461128.380876] cdc_acm 1-4:1.0: ttyACM0: USB ACM devic
```
My user is also part of dialout.
The code builds without issues, I modified the launch file to load up the serial config and tried a couple of different baud rates. I later realized that the baud rate in the config is just the first baud to try and the library actually circles through all baud rates and tries connecting, without success. I get the following error messages:
```
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [urg_node2_node-1]: process started with pid [1623132]
[urg_node2_node-1] [ERROR] [1727775253.153067406] [urg_node2]: Could not open serial Hokuyo 2D LiDAR
[urg_node2_node-1] /dev/ttyACM0:115200
[urg_node2_node-1] could not detect serial baudrate.
[ERROR] [launch_ros.actions.lifecycle_node]: Failed to make transition 'TRANSITION_CONFIGURE' for LifecycleNode '/urg_node2'
```
This suggests the port gets opened fine, but the sensor is not responding as expected. 
Any suggestions as to what might be the issue here? Should I try updating the urg library submodule to a newer version?

**Comment by huangda1982** [comment]
LN-type sensors, including the UST-10LN, are specifically designed for obstacle detection. These sensors are not capable of transmitting measurement data in SCIP protocol, which is required by the urg_library to function properly. Compatible sensor types include:
 LX series
 LA series
 LC series (can switch between LX mode and LA mode)

If your application requires both obstacle detection and data transmission capabilities, I recommend considering the following options:

UST-05LA (USB/RS422)
UST-15LC or UST-30LC (Ethernet)

**Comment by tstoyanov** [comment]
Thanks!

That's a bummer. And a bit embarassing, both for me getting the wrong sensor and for someone designing a laser scanner with two streaming interfaces (USB and RS422) that doesn't stream data... In any case, not a software issue, I will close it. Thanks again!
